### ISSUE TITLE
RC1 tasks

### ISSUE THREAD

**Issue by deepnight** [deepnight/led#1]
**Bugs**

 - [x] Fix GMTK bugs (see #4 )
 - [x] Move grid spacing to RC2 (remove it from current editor)

**Missing features**

 - [ ] Haxe client API (see #7 )
 - [x] Quick save using last filename
 - [x] Implement Tileset deletion
 - [x] Implement Entities sorting
 - [x] Implement Levels sorting
 - [x] Implement Level deletion
 - [x] Level resizing
 - [x] Entity "Enum" values (see #5 )
 - [ ] Project "save as"

**Enhancements**

 - [x] Add Pivot coord for Tiles when layer grid differs from Tileset grid
 - [x] Add a special "one-last-chance" Undo for critical changes (level deletion, layer deletion etc.)

**File format**

- [x] Replace Enum serialization with more human-readable values
- [x] Avoid duplicate identifiers (see #9 )

**Packaging & distrib**

 - [ ] Decide between electron & NWJS
 - [ ] Package a redist
